Hyperledger-TWGC/tape

azure-pipelines.yml

Update Azure pipeline

---

README.md
go.mod
go.sum
infra/config_test.go
infra/observer.go
infra/proposer.go
infra/proposer_test.go
integration-test.sh
main.go

add log with official lib
add more block for testing to see log

add log with logrus lib

---

config.json
integration-test.sh

switch to test-network

---

pkg/infra/observer.go

Check nil message and report

---

pkg/infra/proposer.go

by adding ClientPerConn in loop
Fixes guoger/stupid/#40

Fix for Bug #40

---

cmd/stupid/main.go
e2e/e2e_test.go
go.mod
go.sum
pkg/infra/assembler.go
pkg/infra/client.go
pkg/infra/client_test.go
pkg/infra/config.go
pkg/infra/config_test.go
pkg/infra/observer.go
pkg/infra/proposal.go
pkg/infra/proposer.go
pkg/infra/proposer_test.go

convert all panic into error return with msg
1. Impl
2. Unit test coverage

convert all panic into error return with msg

---

pkg/infra/process.go

fix up for logger

---

pkg/infra/proposer.go

bug fix for #89
those two line in previous version is error msg without panic.
in previous code change, those two error msg cases panic error.
This pr is to fix them back to previous logic.

bug fix for #89

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
docs/gettingstarted.md

update doc as nit fix

---

.github/ISSUE_TEMPLATE/new_feature.md

aims at ref here https://github.com/facebook/create-react-app/tree/master/.github for our template.
for details,  adding lines as bdd/tdd below
Scenario:
if tape supports this feature, then tape user able to benefits
when:
then:

add template for new features

---

docs/whatis.md

更新了文中几个文档的索引

---

azure-pipelines.yml
test/integration-test.sh

Signed-off-by: Yang Cheng <chengyang418@163.com>

update azp for release

---

.github/stale.yml

Add stale bot to auto-close issue

---

azure-pipelines.yml
test/integration-test.sh

Fix CI to pull Fabric release tar with correct version

---

azure-pipelines.yml
pkg/infra/benchmark_test.go
pkg/infra/proposer_test.go

add a workable test suite as performance Benchmark of endorsement

---

README.md

Tidy README.md

---

test/integration-test.sh

update ci scripts as hyperledger/fabric-samples#390 pr changed script behavior.

fix up adjust ci for hyperledger/fabric-samples#390

---

pkg/infra/client.go
pkg/infra/client_test.go
pkg/infra/observer.go
pkg/infra/proposer.go

add auto reconnection logic, when connection create fails.

---

docs/roadmap.md

draft road map

---

Makefile
azure-pipelines.yml
e2e/e2e_test.go
pkg/infra/version.go

Add a makefile, which includes building binary program, building docker, running unit-test and integration-test.
And add commit SHA and built time info in "tape version".
Signed-off-by: wuxu <wuxu1103@163.com>

add Makefile

---

README.md

Add make instructure to readme

---

azure-pipelines.yml
test/integration-test.sh

resolve for #144 and upgrade 1.4 to 1.4.10

---

test/config20org1andorg2.yaml
test/config20selectendorser.yaml
test/integration-test.sh

try to fix ci

---

pkg/infra/benchmark_test.go
pkg/infra/block_collector.go
pkg/infra/block_collector_test.go
pkg/infra/observer.go
pkg/infra/process.go

Block collector as a worker.

---

go.sum
pkg/infra/initiator.go
pkg/infra/initiator_test.go
pkg/infra/process.go
pkg/infra/proposer.go

correct some typos and prune redundant function parameters

fix: code hygiene modification

---

pkg/infra/cmdImpl/process.go
pkg/infra/observer/observer.go
pkg/infra/observer/observerFactory.go

fix up for time setting

---

README.md
azure-pipelines.yml

文档更新，添加了alpha的build badge
提示alpha上添加新的功能
ci更新
添加alpha branch的检查
添加每周自动触发ci的设置

update readme and ci

---

cmd/tape/main.go
e2e/bad_test.go
pkg/infra/cmdImpl/process.go
pkg/infra/trafficGenerator/generatorFactory.go

impl for #173 supports for configurable signers in parallel

impl for #173 supports for configurable signers in parallel

---

README.md

fix up in readme

---

.github/workflows/release.yml

尝试修复github action触发问题
Signed-off-by: DavidLiu <david.yx.liu@oracle.com>

fix trigger

---

pkg/infra/trafficGenerator/proposal.go
pkg/infra/trafficGenerator/proposal_test.go

impl for #200

---

.github/workflows/release.yml
pkg/infra/cmdImpl/fullProcess.go
pkg/infra/observer/block_collector.go
pkg/infra/observer/observer.go
test/integration-test.sh

adding patch for #174

---

cmd/tape/main.go
e2e/TrafficAndObserver_test.go
pkg/infra/cmdImpl/fullProcess.go
pkg/infra/interface.go
pkg/infra/observer/commitObserver.go
pkg/infra/observer/endorsementObersver.go
pkg/infra/observer/observerFactory.go
pkg/infra/trafficGenerator/broadcaster.go
test/integration-test.sh

impl for #213

---

azure-pipelines.yml
e2e/mock/orderer.go
pkg/infra/observer/commitObserver.go
pkg/infra/observer/observerFactory.go

add orderer observer into full workflow process

---

cmd/tape/main.go
pkg/infra/basic/config.go
pkg/infra/basic/logger.go
pkg/infra/cmdImpl/processTemplate.go
pkg/infra/observer/benchmark_test.go
pkg/infra/trafficGenerator/assembler.go
pkg/infra/trafficGenerator/generatorFactory.go
pkg/infra/trafficGenerator/initiator.go
pkg/infra/trafficGenerator/initiator_test.go
pkg/infra/trafficGenerator/intgerator.go
pkg/infra/trafficGenerator/proposal.go
pkg/infra/trafficGenerator/proposer.go
pkg/infra/trafficGenerator/proposer_test.go
test/integration-test.sh

impl for txid tracing at traffic generate

---

pkg/infra/observer/commitObserver.go
pkg/infra/observer/observer.go

try to add tx tracing for observer

---

pkg/infra/basic/logger.go

fix up delete map to avoid OOM

---

.github/workflows/test.yml
test/integration-test.sh

bump CI with fabric 1.4.12

---

Dockerfile
README.md
pkg/infra/basic/logger.go

try to disable jaeger log output by setting logspan to false

---

.github/workflows/test.yml
Dockerfile
azure-pipelines.yml
go.mod
pkg/infra/cmdImpl/fullProcess.go

upgrade to go 1.18

---

pkg/infra/basic/client_test.go
pkg/infra/trafficGenerator/proposer_test.go

upgrade test cases

---

.github/workflows/release.yml
.github/workflows/test.yml

Close #259 
Signed-off-by: DavidLiu <david.yx.liu@oracle.com>

migrate from azure devops to github workflow

---

Makefile
pkg/infra/trafficGenerator/fuzzing_test.go
pkg/infra/trafficGenerator/proposal.go
pkg/infra/trafficGenerator/proposal_test.go
pkg/infra/trafficGenerator/proposer_test.go

support fuzzing

---

.github/workflows/no_func_test.yml
.github/workflows/release.yml
.github/workflows/test.yml
go.mod
pkg/infra/trafficGenerator/proposal.go
test/integration-test.sh

prepare fabric 25

---

.github/workflows/golangci-lint.yml
.golangci.yml

ref https://github.com/golangci/golangci-lint-action/issues/902

try to fix lint issue

---

README.md

add zread for online document. DeepWiki... I failed as don't have google access.

add zread ai document
